### ISSUE TITLE
Is it possible to run this module with Sabaki web version?

### ISSUE THREAD

**Issue by wonsiks** [SabakiHQ/gtp#1]
Hello?

As I'm not a programmer so am not sure about this, but my idea is as follows.

1) Run a gtp go engine(ie. Leela-zero) stand-by to getting connected - must be in the same computer running a web server and contains Sabaki web version and gtp node.js module in it.
2) Connect from other computer(or mobile browser) to Sabaki web version page by connecting to web server.
3) Play go game against the running gtp go engine.

If it'll be possible please let me know how to do it.
It'll gonna be great if possible.

Cheers,

**Comment by yishn** [comment]
Sounds possible with web sockets. Why don't you try asking in a developer forum? This is an issue tracker.
