### ISSUE TITLE
Usage with lz-analyze

### ISSUE THREAD

**Issue by fvictorio** [SabakiHQ/gtp#6]
Hi, thanks for this awesome library.

I'm testing it with leela-zero and I'm wondering how to use it with the `lz-analyze` command. If I check leelaz logs, I see a list of possible plays with their continuations, and what I think are winrates:

```
>>lz-analyze
=
NN eval=0.464540

  S6 ->     318 (V: 25.03%) (LCB: 21.75%) (N: 57.42%) PV: S6 S4 S7 P8 K11 R9 S9 S10 S11 R11 R2 S2 R10 M12 L12 R11 S1
  O8 ->     135 (V: 26.38%) (LCB: 21.20%) (N: 12.21%) PV: O8 O9 S6 S4 P8 Q8 Q9 R9 P9 R8 K11 M12 L13
  Q9 ->      18 (V: 20.52%) (LCB: 10.47%) (N:  7.76%) PV: Q9 P8 S6 S4 S7 R9 S9 R8
  S4 ->      17 (V: 23.62%) (LCB: 10.62%) (N:  3.93%) PV: S4 S3 S6 T4 R7 Q6 O8 O9 P8 Q8 Q9 R9 P9 R8 K11
  R2 ->       6 (V: 18.50%) (LCB:  0.00%) (N:  3.16%) PV: R2 S3 R3 Q4 S4
  R3 ->       4 (V: 15.71%) (LCB:  0.00%) (N:  2.29%) PV: R3 S3 R2 Q4
  P8 ->       4 (V: 15.65%) (LCB:  0.00%) (N:  2.37%) PV: P8 Q8 S6 S4
```

But I don't get any of that information in node. Is there some way to handle this?

Thanks!

**Comment by yishn** [comment]
You're using `lz-analyze` wrong. The correct syntax is `lz-analyze <color> <interval>`, e.g. `lz-analyze b 100`.

**Comment by fvictorio** [comment]
Awesome, thanks!
